

### Listar todas as tarefas
GET http://localhost:3000/tarefas

###

### Buscar tarefa por ID
GET http://localhost:3000/tarefas/

###


### Buscar pelo status
GET http://localhost:3000/tarefas?status=ABERTA

###


### Buscar pelo status e prioridade
GET http://localhost:3000/tarefas?status=ABERTA&prioridade=alta

###


### Criar uma nova tarefa
POST http://localhost:3000/tarefas/
Content-Type: application/json

{

    "titulo": "Testando",
    "descricao": "testando ",
    "prioridade": "ALTA",
    "status": "EM_ANDAMENTO"
}

###

### Deletar uma tarefa
DELETE http://localhost:3000/tarefas/70a794ee-f23f-40b1-9530-052fd8d55ed0

###



### Atualizar uma tarefa existente (Campos completos)
PUT http://localhost:3000/tarefas/f6c6b498-5818-4b0d-89bd-215fc2548f98
Content-Type: application/json

{
    "titulo": "Estudar NestJS e json",
    "descricao": "Praticar integração com gráficos e CRUD de tarefas",
    "prioridade": "media",
    "status": "ABERTA"
}

###

### Atualizar apenas o status de uma tarefa (Atualização parcial)
PUT http://localhost:3000/tarefas/70a794ee-f23f-40b1-9530-052fd8d55ed0
Content-Type: application/json

{
    "status": "EM_ANDAMENTO"
}

###
