# services:
#   postgres_db:
#     image: postgres:16-alpine
#     container_name: container_postgres
#     environment:
#       POSTGRES_USER: tecnook
#       POSTGRES_PASSWORD: "12345"
#       POSTGRES_DB: technook_db
#     ports:
#       - "5432:5432"

#     volumes:
#       - postgres_data:/var/lib/postgresql/data



services:
  postgres_db:
    image: postgres:16-alpine
    container_name: container_postgres
    restart: always
    environment:
      POSTGRES_USER: tecnook
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: technook_db
    ports:
      - "5432:5432"
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_compartilhada

volumes:
  postgres_data:

networks:
  rede_compartilhada:
    external: true